import "./globals.css";
// import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import { UserAuthContextProvider } from "../components/UserAuthContext";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className="flex flex-row">
        <UserAuthContextProvider>{children}</UserAuthContextProvider>
      </body>
    </html>
  );
}
