import "./globals.css";

import { UserAuthContextProvider } from "../components/UserAuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className="flex flex-row">
        <UserAuthContextProvider>{children}</UserAuthContextProvider>
      </body>
    </html>
  );
}
