import "../globals.css";
// import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import Provider from "@/components/Provider/Provider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className="flex flex-row">
        <Provider>
          <Navbar />

          <div className="fixed">
            <Sidebar />
          </div>
          <div className="ml-[14%] w-full mt-24 p-1">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
